FileVersion = 1
Dependencies = {corlib = "*", bgfx-beef = "*", SDL2 = "*"}

[Project]
Name = "example"
StartupObject = "Example.Program"
DefaultNamespace = "Example"

[Configs.Debug.wasm32]
OtherLinkFlags = "$(LinkFlags) -sUSE_SDL=2 -sEXPORTED_RUNTIME_METHODS=requestFullscreen --preload-file $(ProjectDir)/runtime/resources@/"

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) -sUSE_SDL=2 -sEXPORTED_RUNTIME_METHODS=requestFullscreen --preload-file $(ProjectDir)/runtime/resources@/"

[Configs.Paranoid.wasm32]
OtherLinkFlags = "$(LinkFlags) -sUSE_SDL=2 -sEXPORTED_RUNTIME_METHODS=requestFullscreen --preload-file $(ProjectDir)/runtime/resources@/"

[Configs.Test.wasm32]
OtherLinkFlags = "$(LinkFlags) -sUSE_SDL=2 -sEXPORTED_RUNTIME_METHODS=requestFullscreen --preload-file $(ProjectDir)/runtime/resources@/"
