FileVersion = 1

[Project]
Name = "bgfx-beef"

[Configs.Debug.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib user32.lib"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bgfxDebug.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bimgDebug.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bxDebug.lib"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib user32.lib"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bgfxRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bimgRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bxRelease.lib"]

[Configs.Paranoid.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib user32.lib"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bgfxRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bimgRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bxRelease.lib"]

[Configs.Test.Win64]
OtherLinkFlags = "$(LinkFlags) gdi32.lib user32.lib"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bgfxRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bimgRelease.lib", "$(ProjectDir)\\submodules\\bgfx\\.build\\win64_vs2022\\bin\\bxRelease.lib"]

[Configs.Debug.macOS]
OtherLinkFlags = "$(LinkFlags) -framework Cocoa -framework Metal -framework QuartzCore"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbgfxDebug.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbimgDebug.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbxDebug.a"]

[Configs.Release.macOS]
OtherLinkFlags = "$(LinkFlags) -framework Cocoa -framework Metal -framework QuartzCore"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbxRelease.a"]

[Configs.Paranoid.macOS]
OtherLinkFlags = "$(LinkFlags) -framework Cocoa -framework Metal -framework QuartzCore"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbxRelease.a"]

[Configs.Test.macOS]
OtherLinkFlags = "$(LinkFlags) -framework Cocoa -framework Metal -framework QuartzCore"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\osx-x64\\bin\\libbxRelease.a"]

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lGL -lXext -lX11"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbgfxDebug.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbimgDebug.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbxDebug.a"]

[Configs.Release.Linux64]
OtherLinkFlags = "$(LinkFlags) -lGL -lXext -lX11"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbxRelease.a"]

[Configs.Paranoid.Linux64]
OtherLinkFlags = "$(LinkFlags) -lGL -lXext -lX11"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbxRelease.a"]

[Configs.Test.Linux64]
OtherLinkFlags = "$(LinkFlags) -lGL -lXext -lX11"
LibPaths = ["$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbgfxRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbimgRelease.a", "$(ProjectDir)\\submodules\\bgfx\\.build\\linux64_gcc\\bin\\libbxRelease.a"]

[Configs.Debug.wasm32]
OtherLinkFlags = "$(LinkFlags) $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bxDebug.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimgDebug.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimg_decodeDebug.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bgfxDebug.a -sMIN_WEBGL_VERSION=2 -sINITIAL_MEMORY=67108864 -sALLOW_MEMORY_GROWTH=1"

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags) $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bxRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimgRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimg_decodeRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bgfxRelease.a -sMIN_WEBGL_VERSION=2 -sINITIAL_MEMORY=67108864 -sALLOW_MEMORY_GROWTH=1"

[Configs.Paranoid.wasm32]
OtherLinkFlags = "$(LinkFlags) $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bxRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimgRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimg_decodeRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bgfxRelease.a -sMIN_WEBGL_VERSION=2 -sINITIAL_MEMORY=67108864 -sALLOW_MEMORY_GROWTH=1"

[Configs.Test.wasm32]
OtherLinkFlags = "$(LinkFlags) $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bxRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimgRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bimg_decodeRelease.a $(ProjectDir)/submodules/bgfx/.build/wasm/bin/bgfxRelease.a -sMIN_WEBGL_VERSION=2 -sINITIAL_MEMORY=67108864 -sALLOW_MEMORY_GROWTH=1"
